import { test, expect } from '@playwright/test';
import { readFileSync, writeFileSync } from 'node:fs';
import type { Snapshot, Session, Receipt } from '../../src/shared/types';
test('normal presentation screens commit and claim actual test funds and survive retries/refreshes', async ({ page, browser }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  const config = await (await page.request.get('/api/config')).json(); expect(config.presentationReady).toBe(true);
  await page.goto('/'); await page.getByRole('button', { name: 'Employer presentation', exact: true }).click();
  await expect(page).toHaveURL(/\/app$/);
  await expect(page.locator('.native-freshness')).toContainText('Chain synced');
  const workerContext = await browser.newContext({ baseURL: 'http://localhost:3001' }); const worker = await workerContext.newPage();
  await worker.goto('/'); await worker.getByRole('button', { name: 'Worker presentation', exact: true }).click();
  await expect(worker).toHaveURL(/\/app\/portal$/);
  await expect(worker.locator('.native-freshness')).toContainText('Chain synced');
  if (await worker.getByRole('button', { name: 'Confirm managed test recipient' }).count()) {
    await worker.getByRole('button', { name: 'Confirm managed test recipient' }).click();
    await expect(worker.getByRole('button', { name: 'Confirm managed test recipient' })).toHaveCount(0);
  }
  await page.reload();
  const before = await (await page.request.get('/api/bootstrap')).json() as Snapshot;
  expect(before.mode).toBe('testnet'); expect(before.native?.status).toBe('live');
  const receivedBefore = BigInt(before.workers.find(w => w.id === 'presentation_worker')!.received);
  await page.goto('/app/invoices'); await page.getByRole('button', { name: 'New invoice', exact: true }).click();
  const dialog = page.getByRole('dialog'), description = `Real presentation verification ${Date.now()}`;
  await dialog.getByLabel('Work description').fill(description); await dialog.getByLabel('Amount in pathUSD', { exact: true }).fill('1.25');
  await dialog.getByRole('button', { name: 'Create draft invoice', exact: true }).click(); await expect(dialog).not.toBeVisible();
  const created = await (await page.request.get('/api/bootstrap')).json() as Snapshot;
  const createdInvoice = created.invoices.find(i => i.description === description)!;
  const row = page.locator('tr').filter({ hasText: createdInvoice.number });
  await row.getByRole('button', { name: 'Approve', exact: true }).click(); await row.getByRole('button', { name: 'Commit', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Confirm', exact: true }).click();
  await expect(row.getByRole('button', { name: 'Pay now', exact: true })).toBeEnabled();
  const committed = await (await page.request.get('/api/bootstrap')).json() as Snapshot;
  const invoice = committed.invoices.find(i => i.description === description)!;
  expect(invoice.status).toBe('committed'); expect(invoice.commitTransactionRef).toMatch(/^0x[0-9a-f]{64}$/i);
  expect(BigInt(committed.vaults[0].committed) - BigInt(before.vaults[0].committed)).toBe(1_250_000n);
  await page.reload(); await expect(page.locator('tr').filter({ hasText: invoice.number })).toContainText('Committed');
  await worker.reload();
  const workerRow = worker.locator('tr').filter({ hasText: invoice.number });
  await workerRow.getByRole('button', { name: 'Claim payment', exact: true }).click(); await expect(workerRow.getByRole('button', { name: 'Claim payment', exact: true })).toHaveCount(0);
  const paid = await (await worker.request.get('/api/bootstrap')).json() as Snapshot;
  const settled = paid.invoices.find(i => i.id === invoice.id)!;
  expect(settled.status).toBe('paid'); expect(settled.transactionRef).toMatch(/^0x[0-9a-f]{64}$/i); expect(settled.transactionRef).not.toBe(settled.commitTransactionRef);
  expect(BigInt(paid.workers.find(w => w.id === 'presentation_worker')!.received) - receivedBefore).toBe(1_250_000n);
  await workerRow.getByRole('button', { name: `View receipt for ${invoice.number}`, exact: true }).click();
  await expect(worker.getByRole('dialog')).toContainText('Tempo');
  const downloadPromise = worker.waitForEvent('download'); await worker.getByRole('button', { name: 'Download JSON', exact: true }).click();
  const download = await downloadPromise, receipt = JSON.parse(readFileSync((await download.path())!, 'utf8')) as Receipt;
  expect(receipt.mode).toBe('testnet'); expect(receipt.chainId).toBe(42431); expect(receipt.transactionRef).toBe(settled.transactionRef); expect(receipt.amount).toBe('1250000');
  // A different fresh request identity cannot pay a permanent paid claim a second time.
  const session = await (await worker.request.get('/api/auth/session')).json() as Session;
  const duplicate = await worker.request.post(`/api/invoices/${invoice.id}/pay`, { headers: { origin: 'http://localhost:3001', 'x-csrf-token': session.csrfToken, 'x-idempotency-key': `duplicate-${Date.now()}` }, data: {} });
  expect(duplicate.status()).toBe(400);
  const afterDuplicate = await (await worker.request.get('/api/bootstrap')).json() as Snapshot;
  expect(afterDuplicate.workers[0].received).toBe(paid.workers[0].received);
  writeFileSync('public/presentation-flow-evidence.json', JSON.stringify({ network: 'Tempo Moderato', chainId: 42431, verified: true, createdAt: new Date().toISOString(), vault: paid.vaults[0].address, invoiceId: invoice.id, paymentId: invoice.paymentId, amount: receipt.amount, recipient: receipt.recipient, commitHash: invoice.commitTransactionRef, paymentHash: settled.transactionRef, recipientBalanceBefore: receivedBefore.toString(), recipientBalanceAfter: paid.workers[0].received, duplicateRejected: true, receipt }, null, 2) + '\n');
  await page.goto('/app'); await page.screenshot({ path: '.runtime/presentation-dashboard.png', fullPage: true });
  await worker.screenshot({ path: '.runtime/presentation-receipt.png', fullPage: true });
  expect(errors).toEqual([]); await workerContext.close();
});
test('a lost settlement response and reload reuse the saved request identity without paying twice', async ({ page, browser }) => {
  await page.goto('/'); await page.getByRole('button', { name: 'Employer presentation', exact: true }).click();
  await expect(page.locator('.native-freshness')).toContainText('Chain synced');
  const owner = await (await page.request.get('/api/auth/session')).json() as Session;
  const headers = { origin: 'http://localhost:3001', 'x-csrf-token': owner.csrfToken };
  const description = `Lost-response verification ${Date.now()}`;
  const createdResponse = await page.request.post('/api/invoices', { headers: { ...headers, 'x-idempotency-key': `create-${Date.now()}` }, data: { workerId: 'presentation_worker', rail: 'tempo', description, amount: '2000000', dueAt: new Date(Date.now() - 60_000).toISOString() } });
  expect(createdResponse.ok()).toBe(true);
  const created = await createdResponse.json() as Snapshot, invoice = created.invoices.find(i => i.description === description)!;
  expect((await page.request.post(`/api/invoices/${invoice.id}/approve`, { headers: { ...headers, 'x-idempotency-key': `approve-${Date.now()}` }, data: {} })).ok()).toBe(true);
  const commitHeaders = { ...headers, 'x-idempotency-key': `commit-${Date.now()}` };
  const committedResponse = await page.request.post(`/api/invoices/${invoice.id}/commit`, { headers: commitHeaders, data: {} }); expect(committedResponse.ok()).toBe(true);
  const committed = await committedResponse.json() as Snapshot;
  // An exact retry must observe the same commitment; it cannot reserve funds twice.
  const commitRetry = await page.request.post(`/api/invoices/${invoice.id}/commit`, { headers: commitHeaders, data: {} }); expect(commitRetry.ok()).toBe(true);
  expect((await commitRetry.json() as Snapshot).vaults[0].committed).toBe(committed.vaults[0].committed);
  const context = await browser.newContext({ baseURL: 'http://localhost:3001' }); const worker = await context.newPage();
  await worker.goto('/'); await worker.getByRole('button', { name: 'Worker presentation', exact: true }).click();
  await expect(worker.locator('.native-freshness')).toContainText('Chain synced');
  const before = await (await worker.request.get('/api/bootstrap')).json() as Snapshot;
  let completed!: () => void; const responseDiscarded = new Promise<void>(resolve => { completed = resolve; });
  await worker.route(`**/api/invoices/${invoice.id}/pay`, async route => {
    const response = await route.fetch(); expect(response.ok()).toBe(true);
    await route.abort('failed'); completed();
  }, { times: 1 });
  const row = worker.locator('tr').filter({ hasText: invoice.number });
  await row.getByRole('button', { name: 'Claim payment', exact: true }).click(); await responseDiscarded;
  await expect(row.getByRole('cell', { name: 'Paid', exact: true })).toBeVisible();
  await worker.reload(); await expect(worker.locator('tr').filter({ hasText: invoice.number })).toContainText('Paid');
  const pendingKey = await worker.evaluate(invoiceId => {
    const saved = JSON.parse(sessionStorage.getItem('soleil.pending.presentation_worker_user') ?? '[]') as [string, { key: string }][];
    return saved.find(([intent]) => intent.includes(`/api/invoices/${invoiceId}/pay:`))?.[1].key;
  }, invoice.id);
  expect(pendingKey).toBeTruthy();
  const session = await (await worker.request.get('/api/auth/session')).json() as Session;
  const retry = await worker.request.post(`/api/invoices/${invoice.id}/pay`, { headers: { origin: 'http://localhost:3001', 'x-csrf-token': session.csrfToken, 'x-idempotency-key': pendingKey! }, data: {} }); expect(retry.ok()).toBe(true);
  const after = await retry.json() as Snapshot;
  expect(BigInt(after.workers[0].received) - BigInt(before.workers[0].received)).toBe(2_000_000n);
  expect(BigInt(committed.vaults[0].committed) - BigInt(after.vaults[0].committed)).toBe(2_000_000n);
  const paid = after.invoices.find(i => i.id === invoice.id)!;
  writeFileSync('public/presentation-recovery-evidence.json', JSON.stringify({ verified: true, network: 'Tempo Moderato', chainId: 42431, vault: after.vaults[0].address, invoiceId: invoice.id, paymentId: paid.paymentId, commitHash: paid.commitTransactionRef, paymentHash: paid.transactionRef, amount: invoice.amount, recipientBalanceBefore: before.workers[0].received, recipientBalanceAfter: after.workers[0].received, lostResponseRecovered: true, reloadPreservedRequestIdentity: true, exactRetryDeliveredOnlyOnce: true, createdAt: new Date().toISOString() }, null, 2) + '\n');
  await context.close();
});
